# Generated by Django 5.2.1 on 2025-06-06 03:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_identidad', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de identidad solo puede contener números, letras y guiones.', regex='^[0-9A-Za-z-]+$')], verbose_name='Número de identidad')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de contratación')),
                ('direccion_calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('direccion_ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('direccion_codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Presupuesto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoAdministrativo',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservas.empleado')),
                ('nivel_acceso', models.CharField(max_length=20, verbose_name='Nivel de Acceso')),
                ('certificaciones', models.TextField(blank=True, verbose_name='Certificaciones')),
            ],
            options={
                'verbose_name': 'Empleado Administrativo',
                'verbose_name_plural': 'Empleados Administrativos',
            },
            bases=('reservas.empleado',),
        ),
        migrations.CreateModel(
            name='EmpleadoMantenimiento',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservas.empleado')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('herramientas_asignadas', models.TextField(blank=True, verbose_name='Herramientas Asignadas')),
            ],
            options={
                'verbose_name': 'Empleado de Mantenimiento',
                'verbose_name_plural': 'Empleados de Mantenimiento',
            },
            bases=('reservas.empleado',),
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='reservas.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='reservas.empleado', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento_dirigido', to='reservas.empleado', verbose_name='Jefe de Departamento'),
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_habitacion', models.CharField(max_length=10, unique=True, verbose_name='Número de habitación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('informacion_adicional', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON (comodidades, características, etc.)', verbose_name='Información adicional')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En mantenimiento'), ('LIMPIEZA', 'En limpieza')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero_habitacion'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('numero_identidad', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de identidad solo puede contener números, letras y guiones.', regex='^[0-9A-Za-z-]+$')], verbose_name='Número de identidad')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('numero_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de contacto debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de contacto')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_confirmacion', models.CharField(max_length=20, unique=True, verbose_name='Número de confirmación')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha de llegada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de crédito/débito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('PAYPAL', 'PayPal')], max_length=15, verbose_name='Método de pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.huesped', verbose_name='Huésped')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-fecha_llegada'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ReservacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario')),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reservacion', verbose_name='Reservación')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Reservación-Servicio',
                'verbose_name_plural': 'Reservaciones-Servicios',
            },
        ),
        migrations.CreateModel(
            name='TelefonoHuesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('casa', 'Casa'), ('trabajo', 'Trabajo')], max_length=20, verbose_name='Tipo')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='reservas.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Teléfono de Huésped',
                'verbose_name_plural': 'Teléfonos de Huéspedes',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(choices=[('SENCILLA', 'Sencilla'), ('DOBLE', 'Doble'), ('MATRIMONIAL', 'Matrimonial'), ('SUITE_JUNIOR', 'Suite Junior'), ('PRESIDENCIAL', 'Presidencial')], max_length=20, unique=True, verbose_name='Tipo de habitación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad_personas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad de personas')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio base')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.tipohabitacion', verbose_name='Tipo de habitación'),
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Dependiente',
                'verbose_name_plural': 'Dependientes',
                'unique_together': {('empleado', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20, verbose_name='Turno')),
                ('tareas_realizadas', models.TextField(blank=True, verbose_name='Tareas Realizadas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.empleado', verbose_name='Empleado')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'unique_together': {('empleado', 'habitacion', 'fecha', 'turno')},
            },
        ),
    ]
