# Generated by Django 5.2.1 on 2025-05-27 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_habitacion', models.CharField(max_length=10, unique=True, verbose_name='Número de habitación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('informacion_adicional', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON (comodidades, características, etc.)', verbose_name='Información adicional')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En mantenimiento'), ('LIMPIEZA', 'En limpieza')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero_habitacion'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('numero_identidad', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de identidad solo puede contener números, letras y guiones.', regex='^[0-9A-Za-z-]+$')], verbose_name='Número de identidad')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('numero_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de contacto debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de contacto')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('numero_confirmacion', models.CharField(max_length=20, unique=True, verbose_name='Número de confirmación')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha de llegada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de crédito/débito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('PAYPAL', 'PayPal')], max_length=15, verbose_name='Método de pago')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.huesped', verbose_name='Huésped')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['-fecha_llegada'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(choices=[('SENCILLA', 'Sencilla'), ('DOBLE', 'Doble'), ('MATRIMONIAL', 'Matrimonial'), ('SUITE_JUNIOR', 'Suite Junior'), ('PRESIDENCIAL', 'Presidencial')], max_length=20, unique=True, verbose_name='Tipo de habitación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('capacidad_personas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad de personas')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio base')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.tipohabitacion', verbose_name='Tipo de habitación'),
        ),
    ]
